name: tests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.4
      - name: Install dependencies
        run: |
          poetry install
      - name: Pytest
        run: |
          poetry run pytest
        env:
          MOCKFORCE_RELATIONS_ROOT: tests
      - name: Slack Notifications
        uses: Kicksaw-Consulting/notify-slack-action@master
        if: always()
        with:
          status: ${{ job.status }}
          notify_when: "failure"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          STAGE: test
